# .github/workflows/image.yml
# GitHub secrets:
# DOCKER_USERNAME
# DOCKER_PASSWORD
# DOCKER_REPOSITORY

name: Building docker containers
on:
  push:
    branches: main
jobs:
  building:
    runs-on: ubuntu-latest
    steps:
      - name: setup-docker
        uses: docker-practice/actions-setup-docker@master

      - name: checkout code
        uses: actions/checkout@v2

      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: build the image
        run: |
          docker buildx build --push \
            --tag "${{ secrets.DOCKER_USERNAME }}"/"${{ secrets.DOCKER_REPOSITORY }}":latest \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .
