# .github/workflows/image.yml
# GitHub secrets:
# DOCKER_USERNAME
# DOCKER_PASSWORD
# DOCKER_REPOSITORY

name: Building docker containers
on:
  push:
    branches: main
jobs:
  building:
    runs-on: ubuntu-latest
    steps:
      - name: setup-docker
        uses: docker-practice/actions-setup-docker@master

      - name: checkout code
        uses: actions/checkout@v2

      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: build the image for amd64
        run: |
          docker build -t "${{ secrets.DOCKER_USERNAME }}"/"${{ secrets.DOCKER_REPOSITORY }}":latest-amd64 --build-arg ARCH=amd64/ -f Dockerfile . &&\
          docker push "${{ secrets.DOCKER_USERNAME }}"/"${{ secrets.DOCKER_REPOSITORY }}":latest-amd64

      - name: build the image for arm32v7
        run: |
          docker build -t "${{ secrets.DOCKER_USERNAME }}"/"${{ secrets.DOCKER_REPOSITORY }}":latest-arm32v7 --build-arg ARCH=arm32v7/ -f Dockerfile.armhf . &&\
          docker push "${{ secrets.DOCKER_USERNAME }}"/"${{ secrets.DOCKER_REPOSITORY }}":latest-arm32v7

      - name: build the image for arm64v8
        run: |
          docker build -t "${{ secrets.DOCKER_USERNAME }}"/"${{ secrets.DOCKER_REPOSITORY }}":latest-arm64v8 --build-arg ARCH=arm64v8/ -f Dockerfile.aarch64 . &&\
          docker push "${{ secrets.DOCKER_USERNAME }}"/"${{ secrets.DOCKER_REPOSITORY }}":latest-arm64v8

      - name: create manifest
        run: |
          docker manifest create \
          "${{ secrets.DOCKER_USERNAME }}"/"${{ secrets.DOCKER_REPOSITORY }}":latest \
          --amend "${{ secrets.DOCKER_USERNAME }}"/"${{ secrets.DOCKER_REPOSITORY }}":latest-amd64 \
          --amend "${{ secrets.DOCKER_USERNAME }}"/"${{ secrets.DOCKER_REPOSITORY }}":latest-arm32v7 \
          --amend "${{ secrets.DOCKER_USERNAME }}"/"${{ secrets.DOCKER_REPOSITORY }}":latest-arm64v8 
            
      - name: push the manifest
        run: |
          docker manifest push "${{ secrets.DOCKER_USERNAME }}"/"${{ secrets.DOCKER_REPOSITORY }}":latest
